import csv
from fpdf import FPDF

# Define the PDF invoice class
class Invoice(FPDF):
    def __init__(self):
        super().__init__()  # Initialize the FPDF base class
        self.unifontsubset = False
    
    def header(self):
        # Add your custom header here
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "Automate & Analyze with Amy", 0, 1, "C")
        self.set_y(60)  # Move the cursor down after adding the logo

    def footer(self):
        # Add your custom footer here
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by Amy's Invoice Generator", 0, 0, "C")

    def create_invoice(self, row):
        self.set_font("Arial", size=12)  # Set the font before adding content
        invoice_content = self.generate_invoice_content(row)
        self.multi_cell(0, 10, invoice_content)

    def generate_invoice_content(self, row):
        invoice_content = f"Invoice Number: {row[0]}\n"
        invoice_content += f"Customer Name: {row[2]}\n"
        invoice_content += f"Address: {row[3]}\n"
        invoice_content += f"Total Amount: {row[7]}\n"
        return invoice_content

# Read the CSV file
csv_file = "C:/Users/amymi/OneDrive/Automate and Analyze with Amy/Development/Automated-Invoice-Generator/files/invoices.csv"

with open(csv_file, "r") as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row

    # Iterate over each record in the CSV file
    for row in reader:
        # Create a new PDF invoice
        pdf = Invoice()
        pdf.add_page()

        # Generate the invoice content
        pdf.create_invoice(row)

        # Save the PDF invoice
        invoice_number = row[0]
        pdf_file = f"invoice_{invoice_number}.pdf"
        pdf.output(pdf_file)

        print(f"Generated PDF invoice: {pdf_file}")